@header@
.
.Sh NAME
.Nm Jas(per), Jaz
.Nd chronic overthinker, computer enthusiast (they/he)
.Sh SYNPOSIS
.Pp
Hi, I'm Jasper. This is my website, where I overshare on the internet. It's
good for the soul.
.Pp
I'm a 25-year-old non-binary femboy, whatever that means. I prefer they/them
pronouns, but he/him is okay too. I just ask that you're respectful about it.
.Pp 
I'm interested in video games, linux systems, and sustainable living. I'd like
to make more art, physical and digital, and maybe make a video game one day.
I also stream on Twitch
.Lk https://www.twitch.tv/jaspinegz here ,
where I play games like Celeste, Hollow Knight, Valorant, and sometimes write
code. Feel free to tune in. :)
.Pp
For money, I do odd things. Right now, I do surveys for an ecology company. I
try to keep out of the corporate sphere, because it just makes me depressed.
.Pp
I use Nix for most things, including as a template engine for this blog. This
blog is open-source, along with the rest of my infrastructure.
.Pp
Some other things I'm interested in: playing guitar, piano, watering my plants
(when I remember, which isn't very often), capybaras, and whimsy wherever I can
get away with it. ♡
.Bd -literal -decorate "aside aside-h" 
__HTML
<canvas id="aside-animated-plant" width=120 height=423></canvas>
<script>
let canvas = document.getElementById("aside-animated-plant");
let ctx    = canvas.getContext("2d");
ctx.fillStyle = "red";
ctx.fillRect(10, 10, 150, 150);
</script>
__ENDHTML
.Ed
.Pp
.Lk https://weirdfi.sh/posts posts
\(em
.Lk https://git.weirdfi.sh code
.Ss UPDATES
@updates@
