@header@
@back@
.Sh NAME
.Nm @title@
.Nd @description@
.Sh DESCRIPTION
.Bd -literal -decorate info
This post will be a little manic due to sleepyness. My sleep schedule seems to
invert itself every 11 days at the moment. I think it's a "Non-24-hour
sleep–wake disorder", but my friends think it's "unemployment". Go figure.
.Ed
I've had commitment issues for a long time now. Typically, this phrase is used
specifically to refer to difficulities in relationships; namely, staying in
them for very long. But my commitment issues are broader than that.
.Pp
Most people, as they get older, start to accumulate some goals. I think
everybody does. A goal can be small, like purchasing a potted plant, or
something more significant, like making a painting. Actually, the size of a
goal seems to be fairly unbounded, except that certain goals are just silly to
have. Like, you could have a goal to breathe, but you were going to do that
anyway, hopefully. Or your goal could be to turn all atomic matter into
paperclips, but that's not actually possible, hopefully. It's also generally a
bad idea.
.Pp
I've certainly accumulated a lot of goals so far in my life. If you know me,
you probably know I've been meaning to make Bench (an open-source replacement
for Discord; what TeamSpeak 5 should've been) for like 12 years. Unfortunately
that's not an exaggeration. I've had lots of other goals too. At one point I
really wanted to open a public Minecraft server. At another point I really
wanted to make a video game. I've wanted to make a few different games,
actually. I wanted to make a note-taking software which would be a bit like
Notion.
.Pp
I had a really big goal at one point; I wanted to open a restaurant or cafe
before I was 30 years old. I was really into cooking at that point in my life,
making new recipes each day, writing exactly none of them down. Nowadays, 30 is
looking a little soon. Maybe I'll try for 40? Also, cafe sounds better. Coffee
is a need.
.Pp
Everybody has goals, and those goals will change over time. My goals have
definitely changed a lot. I used to think about little else other than hitting
Immortal in VALORANT. Now, I still think about hitting Immortal in VALORANT,
but I also think about learning to crochet, amongst other things.
.Pp
But I realized something tonight. None of my goals get done. I think about them
often, but no progress gets made. I wondered if it was a routine problem, or a
discipline problem, or if I just didn't want them hard enough. People on the
internet say that sometimes. If you're not working towards your goals, you must
not really want to achieve them. I wondered if I was just lazy. My running
theory is this: I don't believe I can actually achieve them.
.Pp
The truth is, the goals I really care about all require a substantial,
sustained effort to achieve. I can only think of one time I've really tried to
put this kind of effort into a goal, and that was in college. I took four
subjects during my A-Levels, which isn't necessarily that challenging, but it
was unusual in my college. I didn't study much throughout the first year and a
half. The work felt easy enough, despite some confusing topics here and there,
and my teachers all expected me to do well.
.Pp
So far, I hadn't needed to study to do well in school. I just paid attention in
lessons, understood the content conceptually, then applied that understanding
in the exams. Maybe some people can just do this their whole lives, never once
being reality checked by the limitations of their own cognitive substrate.
Unfortunately, this was not me, and so I realized I had to study.
.Pp
There are a few things it seems you don't learn until it's too late. Firstly,
that studying itself is a skill. With college exams, all they expect,
basically, is regurgitation of information. You must learn how to take the
information, save it in your brain, and reproduce it later. Secondly, you don't
know how much you don't know, so until you start to test your knowledge, you
won't know how much studying you have to do. Finally, that you probably have
ADHD, and you're only motivated by stress, your hyperfixations, or the promise
of an instantaneous dopamine delivery.
.Pp
I really did try my hardest in the three months coming up to my exams. The
details are foggy now, but I know I didn't _actually_ do that much studying. In
principle, I really wanted to succeed, but I didn't understand how to make
myself put in the effort towards that goal. In fact, it's been more than seven
years since those exams, and I'm still pretty far from understanding how to
push past the excruciating boredom of an understimulating, yet mentally
labourous task. 18-year-old me didn't stand a chance.
.Pp
I've never been as disappointed as when I received my A-Level results. It made
sense, of course, because I knew that I hadn't studied enough. But it was still
a shock. I had wanted to do well so badly, but wanting to do well didn't seem
to be enough. My brain had refused to cooperate, and reality had finally caught
up to me.
.Pp
I try to resist defining myself by that disappointment. But I've known for a
while that it majorly damaged by confidence. Those three months of studying, on
and off, is my longest period of sustained effort to date. Since then, nothing
has really come close. My most substantial project was probably my dissertation
since, which I largely implemented and wrote during a 5-day period immediately
before the deadline. Like I said, only motivated by stress.
.Pp
I think that, put simply, the reason I don't work towards my goals is that I
don't believe I can achieve them. And I don't believe I can achieve them
because I've never achieved anything like them before. My most important goals
are really substantial. A video game, for example, depending on its scope, can
be a huge project, even just in the conception of its contents, let alone its
execution. A truly feasible Discord alternative would be a really challenging
endevour. And as I change, and so do my goals, and I start to think about even
bigger goals
.\(Em
_life_ goals
.\(Em
this only becomes more true.
.Pp
So, where do I go from here? Well, if this is really why I've been putting
things off, I think I should start with convincing myself that I am capable of
achieving things that I set my mind to. I should start with small goals, taking
pride in each accomplishment as they come, and work my way up to larger
projects. So that's what I'm going to do. And, where it makes sense, I'll
upload my accomplished goals to this site, and slowly build an undeniable
record for myself of the things that I'm capable of.
.Pp
BTW, there is one sustained effort that I've managed to stick to since back
then: this website. I know there's not much here yet, but it's really the first
thing I've worked towards for more than a month for a long, long time. I teared
it down and rebuilt it from scratch many times, but I didn't give up, and now
here it is. And everybody knows I have a website, because I won't shut up about
it. I'm so happy that I made it. 
.Pp
Thank you for reading.
.Pp
@back-posts@
.Sh CHANGELOG
.Bl -enum
stub
.Sh AUTHORS
Jasper Pine / jaspine
.Sh FOOTNOTES
.Bl -enum 
stub
.Ed
